"""Add location 2

Revision ID: 9f1ed8ea961f
Revises: 0b3c80b2a5cb
Create Date: 2023-11-25 16:24:57.268264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1ed8ea961f'
down_revision: Union[str, None] = '0b3c80b2a5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.Enum('Nicosia', 'Limassol', 'Larnaca', 'Pafos', name='location'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'location')
    # ### end Alembic commands ###
