"""Add enum 2

Revision ID: ab761a19c459
Revises: ebe600c9e861
Create Date: 2023-11-26 14:17:07.275545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab761a19c459'
down_revision: Union[str, None] = 'ebe600c9e861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'created_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'join_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    op.execute("ALTER TYPE tags ADD VALUE 'AIRPORT';")
    op.execute("ALTER TYPE tags ADD VALUE 'DELAY';")
    op.execute("ALTER TYPE tags ADD VALUE 'MARATHON';")
    op.execute("ALTER TYPE tags ADD VALUE 'BASKETBALL';")
    op.execute("ALTER TYPE tags ADD VALUE 'SCIENCE';")
    op.execute("ALTER TYPE tags ADD VALUE 'TECHNOLOGY';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthdate',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('users', 'join_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('events', 'created_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
